# Generated by Django 5.0.6 on 2024-05-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
